#For help with how to configure this plugin please refer to the wiki!

#Enter MySQL database information below
DataStore:
  user: root #Username for the database
  password: pass #Password for the user
  databaseURL: localhost:3306/fuedalism #URL of the database || template: [IP]:[PORT]/[DATABASE]
  
AllyRequest:
  daysToExpire: 7 #Sets how soon alliance requests expire

CommandBlocking:
  blockedInEnemyClaim: #List of commands blocked inside enemy claims
    -f
  blockDistanceNearPlayer: 20 #Distance a player needs to be from enemy players to use blocked commands
  blockedNearEnemyPlayer: #List of commands blocked near enemy players
    -f