name: Governance
author: StevenMG
version: 1.0.1
main: org.theglicks.bukkit.governance.Governance
website: http://dev.bukkit.org/bukkit-mods/gp-factions/
description: A land claiming and PVP plugin inspired by Grief Prevention and Factions
depend: [Vault]

commands:
  kingdom:
    description: Base command to manage kingdoms
    permission: governance.basic
    permission-message: You do not have permission to use this command!
    aliases: k
  fief:
    description: Base command to manage fiefs
    permission: governance.basic
    permission-message: You do not have permission to use this command!
    aliases: f